//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExerciseTable
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Exercise { get; set; }
        public string MuscleGroup { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> Sets { get; set; }
        public Nullable<int> Reps { get; set; }
    }
}
